services:
  backend:
    build: ./docker/Dockerfile.backend
    ports:
      - "5000:5000"
    preprocessor:
      build: ./docker/Dockerfile.preprocessor
      ports:
        - "6000:6000"
    solver:
      build: ./docker/Dockerfile.solver
      ports:
        - "7000:7000"
    mongo:
      image: mongo
      ports:
        - "27017:27017"


        # version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile.backend
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongo
#       - preprocessor
#       - solver

#   preprocessor:
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile.preprocessor
#     ports:
#       - "6000:6000"

#   solver:
#     build:
#       context: .
#       dockerfile: ./docker/Dockerfile.solver
#     ports:
#       - "7000:7000"

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
